//create rock paper scissors variables,
//create win lose draw variables,
//create score variables,
//generate function to return rock paper or scissors randomly,
//generate function to return user's input,
//generate function to start a rock paper scissors round against the computer
//show computer selection on console log,
//show player selection on console log,
//generate if else for when player and computer choose rock paper or scissors,
//show computer score on console log,
//show player score on console log,
//generate a function that invokes the game start function 5 times,